title: RxHive
description: RxHive is an open-source platform built on Jekyll, designed to collaboratively construct a comprehensive medicine database. By combining AI-generated content and crowd-sourced contributions, RxHive empowers healthcare professionals, researchers, and the wider community to build a reliable, ever-evolving repository of drug and treatment information.
theme: just-the-docs

url: https://rxhive.zynapte.com
baseurl: "https://rxhive.zynapte.com"

# Collections configuration
collections:
  generic:
    output: true
    permalink: /generic/:path/
  composition:
    output: true
    permalink: /composition/:path/

just_the_docs:
  collections:
    generic:
      name: Generic
      nav_exclude: true    # Exclude the collection from main navigation
      nav_fold: true       # Fold collection pages in navigation (if included later)
      output: true
    composition:
      name: Composition
      nav_exclude: true    # Exclude the collection from main navigation
      nav_fold: true       # Fold collection pages in navigation (if included later)
      output: true
  footer_content: "Made with ❤️ at <a href='https://www.zynapte.com'>Zynapte</a> and the <a href='https://www.github.com'>GitHub Community</a>."
  last_edit_timestamp: true
  last_edit_time_format: "%b %e %Y at %I:%M %p"
  gh_edit_link: true
  gh_edit_link_text: "Edit this page on GitHub."
  gh_edit_repository: "https://github.com/RxHive/RxHive.github.io"
  gh_edit_branch: "main"
  gh_edit_view_mode: "tree"

# Default layout and options for generic collection
defaults:
  - scope:
      path: "generic/"
    values:
      layout: "default"  # Use default layout for generic pages
      output: true

# Include generic folder in processing
include:
  - generic
  - composition
  - robots.txt
  - google46cc0abefa86d150.html

# Plugins
plugins:
  - jekyll-sitemap

# Exclude specific files and folders from the sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/

# Sitemap settings (optional)
sitemap:
  filename: sitemap.xml # Default is sitemap.xml
  exclude:
    - /404.html
ga_tracking: G-JMBXT0N7K0
ga_tracking_anonymize_ip: true 